### ISSUE TITLE
Totally crashed my craft installation

### ISSUE THREAD

**Issue by gudehus** [bitboxde/minifier#3]
after updating I got this error
Calling unknown method: bitboxde\minifier\services\View::minify()
installed everything from scratch and after installing the plugin, boom, same error.

**Comment by bitboxrk** [comment]
That was strange! Some files and some new methods were missing on the last commit for version 2.0.0. That has never happend before! I'm sorry for this embarrassing mistake. It's now fixed and everything should work fine.
