### ISSUE TITLE
JS - Footer in Head

### ISSUE THREAD

**Issue by thefubon** [bitboxde/minifier#9]
Please tell me how to display JS files not in the FOOTER but in HEAD
``` {% do minifier.view.registerJsFile('/uikit.js') %}```

**Comment by bitboxfw** [comment]
Just use position: POS_HEAD

```
{% do minifier.view.registerJsFile('/uikit.js', {position: POS_HEAD}) %}
```

**Comment by thefubon** [comment]
Thank you so much!
